[package]
org = "wso2healthcare"
name = "metadata_api"
version = "0.1.5"
export = ["metadata_api.config","metadata_api.constants","metadata_api.handlers","metadata_api.models","metadata_api.samples"]
distribution = "2201.2.3"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Metadata"]

[build-options]
observabilityIncluded = true
