[package]
org = "wso2healthcare"
name = "patient_api"
version = "0.1.3"
export = ["patient_api"]
distribution = "2201.2.3"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Patient","r4","international"]

[build-options]
observabilityIncluded = true
